import { GameState, createEmptyBoard } from '../../types';

export const initialState: GameState = {
  board: createEmptyBoard(),
  vertices: {},
  playerHand: [],
  opponentHand: [],
  playerSiteDeck: [],
  playerSpellDeck: [],
  opponentSiteDeck: [],
  opponentSpellDeck: [],
  playerGraveyard: [],
  opponentGraveyard: [],
  playerSpellStack: [],
  opponentSpellStack: [],
  playerCollection: [],
  opponentCollection: [],
  playerLife: 20,
  opponentLife: 20,
  playerMana: 0,
  playerManaTotal: 0,
  opponentMana: 0,
  opponentManaTotal: 0,
  playerThresholds: { air: 0, earth: 0, fire: 0, water: 0 },
  opponentThresholds: { air: 0, earth: 0, fire: 0, water: 0 },
  currentTurn: 'player',
  turnNumber: 1,
  turnStarted: false,
  hoveredCard: null,
  hoveredDeck: null,
  shufflingDeck: null,
  harbingerMarkers: [],
};
